// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7qtq8wPqgG87JxjigoLUkaShDK27YvHI',
    appId: '1:779393698703:web:62a3fbe9a6209edca6d9fa',
    messagingSenderId: '779393698703',
    projectId: 'lip-sync-voice',
    authDomain: 'lip-sync-voice.firebaseapp.com',
    storageBucket: 'lip-sync-voice.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5tWmPiy-b2cwKf2ddPmbhOJU_i_QohHU',
    appId: '1:779393698703:android:fe490558213c3e7da6d9fa',
    messagingSenderId: '779393698703',
    projectId: 'lip-sync-voice',
    storageBucket: 'lip-sync-voice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi3h1PVdZZWfJouc_Fwz_YfX4StfM4gus',
    appId: '1:779393698703:ios:984a4a1bcf729c99a6d9fa',
    messagingSenderId: '779393698703',
    projectId: 'lip-sync-voice',
    storageBucket: 'lip-sync-voice.appspot.com',
    iosBundleId: 'com.example.lipsyncvoiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi3h1PVdZZWfJouc_Fwz_YfX4StfM4gus',
    appId: '1:779393698703:ios:9ffaeaf8b4e329cda6d9fa',
    messagingSenderId: '779393698703',
    projectId: 'lip-sync-voice',
    storageBucket: 'lip-sync-voice.appspot.com',
    iosBundleId: 'com.example.lipsyncvoiceApp.RunnerTests',
  );
}
